services:
  spongout:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spongout
    image: pmackiewicz6/spongout-image:v1
    ports:
      - "80:8099"
    restart: unless-stopped