server:
  port: 8099
spring:
  application:
    name: SpongFu

# it should go to .env but didnt have time for that
app:
  config:
    game:
      min-players-to-start: 2
      max-players-in-lobby: 5
      countdown-seconds: 5
      round-max-seconds: 20
      arena-initial-radius: 500.0
      player-starting-size: 20.0
      tick-rate-ms: 16 # 16 = about 60fps (1000/60)

      player-growth-rate: 6.0 # Mass per second
      player-spin-rate-rad: 4 # Math.PI * 2 (Radians per second, 1 full rotation)
      friction-factor: 0.5 # Multiplier per frame
      sudden-death-ms: 5000 # 5 seconds
      arena-shrink-rate: 15.0 # Radius units per second
      launch-power-multiplier: 12

# Add logging configuration for WebSocket/STOMP debugging
logging:
  level:
    com.spongout.spongout: DEBUG
    org:
      springframework:
        messaging: INFO
        web:
          socket: INFO